### ISSUE TITLE
Research on how to store data in database using MySQL

### ISSUE THREAD

**Issue by guninkakar03** [utmgdsc/MyAcademia#15]
The aim is develop a database that supports existing functionality of the Degree explorer. The tables will include data that keeps track of courses that are offered at UTM, programs that are offered, and other important data associated to the same.

**Comment by guninkakar03** [comment]
We need a database that is essentially common for both the Degree explorer extension of our project and the sentiment analysis one. The basic fields in the first table can be:

1. Course code (eg. CSC108)
2. Course Title (eg. Intro To programming)
4. Credit (eg. 0.5 )
5. Distribution (eg. SCI)
6. Recommended Prep 
7. Prerequisites
8. Exclusions

Note: We would need more table to effectively handle the prerequisites and exclusions.

**Comment by guninkakar03** [comment]
![utmCourseDatabase@localhost](https://github.com/utmgdsc/MyAcademia/assets/79251416/fe9c4838-b687-40ee-876d-633a4d7fb74c)
The final design of the database!

**Comment by adityaharish218** [comment]
Have implemented the da
