### ISSUE TITLE
Design the layout of the project

### ISSUE THREAD

**Issue by AkhilChoraria** [utmgdsc/MyAcademia#22]
Features:
- Login Page
- Course-info Tab : Course Description, Pre-Requisites, Reviews, Implement Existing Filters and expand on it.
- Allow user to write reviews for courses
- Implement a text based suggestion search.
- Degree Explorer Tab: User Input courses, Program Information, Generate Button, Outputs the possible study plan for the user, possibly grades of the user.

Design-Doc inclusions:

Diagrams:
- The login Page API, Login Database, Associated Servers.
- Course Database, Reviews API, Sentiment Analysis API
- Degree Explorer API, Course Database, Program Database

Technical Stack:
- Python/JS Frameworks: Django and React for Front and Backend
- Setting up the Database: MySql
- Web Scraping: Beautiful Soup
- Rest API

Product Backlog:
- Login Page: Login Page API, Login Page Frontend, Login Page Backend
- User Stories
- Timeline
- Milestones
- Deployment
- UML Diagrams

**Comment by guninkakar03** [comment]
Google Doc:  https://docs.google.com/document/d/1f16ubTCmoDj11mObebN4Ky4POxZLRimjdJ0xWfvvLR0/edit?usp=sharing

**Comment by AkhilChoraria** [comment]
Completed the Design Document and submitted it to Professor Bahar for feedback.
